#!/usr/bin/env python3

import socket
import json
import ssl
from server import Server

class TLSServer(Server):
    port = 27994
    hostname = "127.0.0.1"
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
        s.bind((hostname, port))
        s.listen()
        sslSock = context.wrap_socket(sock=s, server_side=True)
        print("Socket connection opened and listening...")
        mysocket, addr = sslSock.accept()
        with mysocket:
            server = Server(mysocket)
            while True:
                data = json.loads(mysocket.recv(25600).decode())
                print(data)
                if server.typeParser(data) == False:
                    break  
            mysocket.shutdown(socket.SHUT_RDWR)
            mysocket.close()
        s.shutdown(socket.SHUT_RDWR)
        s.close()  